export type { DialogCloseProps } from './close'
export { DialogClose, DialogClose as Close } from './close'
export type { DialogContentProps } from './content'
export { DialogContent, DialogContent as Content } from './content'
export type { DialogDescriptionProps } from './description'
export { DialogDescription, DialogDescription as Description } from './description'
export type { DialogProps } from './dialog'
// Short aliases for namespace-style imports
export { createDialogScope, Dialog, Dialog as Root, getState, WarningProvider } from './dialog'
export type { DialogOverlayProps } from './overlay'
export { DialogOverlay, DialogOverlay as Overlay } from './overlay'
export type { DialogPortalProps } from './portal'
export { DialogPortal, DialogPortal as Portal } from './portal'
export type { DialogTitleProps } from './title'
export { DialogTitle, DialogTitle as Title } from './title'
export type { DialogTriggerProps } from './trigger'
export { DialogTrigger, DialogTrigger as Trigger } from './trigger'
