export type { IDialogCloseProps } from './close'
export { DialogClose, DialogClose as Close } from './close'
export type { IDialogContentProps } from './content'
export { DialogContent, DialogContent as Content } from './content'
export type { IDialogDescriptionProps } from './description'
export { DialogDescription, DialogDescription as Description } from './description'
export type { IDialogProps } from './dialog'
// Short aliases for namespace-style imports
export { createDialogScope, Dialog, Dialog as Root, getState, WarningProvider } from './dialog'
export type { IDialogOverlayProps } from './overlay'
export { DialogOverlay, DialogOverlay as Overlay } from './overlay'
export type { IDialogPortalProps } from './portal'
export { DialogPortal, DialogPortal as Portal } from './portal'
export type { IDialogTitleProps } from './title'
export { DialogTitle, DialogTitle as Title } from './title'
export type { IDialogTriggerProps } from './trigger'
export { DialogTrigger, DialogTrigger as Trigger } from './trigger'
