export type { SliderProps } from './slider'
export { createSliderScope, Slider, Slider as Root } from './slider'
export type { SliderRangeProps } from './slider-range'
export { SliderRange, SliderRange as Range } from './slider-range'
export type { SliderThumbProps } from './slider-thumb'
export { SliderThumb, SliderThumb as Thumb } from './slider-thumb'
export type { SliderTrackProps } from './slider-track'
export { SliderTrack, SliderTrack as Track } from './slider-track'
