export type { ISliderProps } from './slider'
export { createSliderScope, Slider, Slider as Root } from './slider'
export type { ISliderRangeProps } from './slider-range'
export { SliderRange, SliderRange as Range } from './slider-range'
export type { ISliderThumbProps } from './slider-thumb'
export { SliderThumb, SliderThumb as Thumb } from './slider-thumb'
export type { ISliderTrackProps } from './slider-track'
export { SliderTrack, SliderTrack as Track } from './slider-track'
