import type { Metadata, Viewport } from 'next'
import { absoluteUrl } from '~/lib'
import { siteConfig } from './site'

export const VIEWPORT: Viewport = {
  themeColor: [
    { color: 'white', media: '(prefers-color-scheme: light)' },
    { color: 'black', media: '(prefers-color-scheme: dark)' },
  ],
}

export const METADATA: Metadata = {
  alternates: {
    canonical: siteConfig.url,
  },
  authors: [
    {
      name: 'wildduck2',
      url: 'https://github.com/wildduck2',
    },
  ],
  creator: 'wildduck2',
  description: siteConfig.description,
  icons: {
    apple: '/apple-touch-icon.png',
    icon: '/favicon.ico',
    shortcut: '/favicon-96x96.png',
  },
  keywords: [
    'gentleduck',
    'gentleduck org',
    'gentleduck ecosystem',
    'gentleduck packages',
    'gentleduck/ui',
    'React UI library',
    'Tailwind CSS components',
    'styled React components',
    'shadcn alternative',
    'production-ready UI components',
    'gentleduck/primitives',
    'headless UI components React',
    'accessible React primitives',
    'Radix alternative',
    'unstyled React components',
    'gentleduck/cli',
    'React UI CLI',
    'component scaffolding CLI',
    'install React components CLI',
    'gentleduck/calendar',
    'React calendar component',
    'headless calendar engine',
    'React date picker',
    'react-day-picker alternative',
    'React Persian calendar',
    'React Hijri calendar',
    'date adapter pattern',
    'gentleduck/variants',
    'cva React',
    'type-safe component variants',
    'class variance authority alternative',
    'gentleduck/vim',
    'React keyboard shortcuts',
    'keyboard command engine',
    'vim keybindings React',
    'gentleduck/motion',
    'React animation library',
    'mount unmount transitions React',
    'reduced motion React',
    'gentleduck/state',
    'React atom state management',
    'lightweight React state',
    'gentleduck/hooks',
    'reusable React hooks',
    'React utility hooks',
    'gentleduck/libs',
    'React utility library',
    'cn utility TypeScript',
    'gentleduck/lazy',
    'React lazy loading components',
    'deferred React components',
    'gentleduck/shortcut',
    'React keyboard shortcut hooks',
    'power-user React interface',
    'gentleduck/ttlog',
    'structured logging TypeScript',
    'type-safe terminal logger',
    'pluggable log transports',
    'gentleduck/upload',
    'file upload library TypeScript',
    'multipart upload JavaScript',
    'chunked file upload',
    'presigned URL upload',
    'gentleduck/iam',
    'identity access management TypeScript',
    'role based access control JavaScript',
    'RBAC TypeScript',
    'policy enforcement library',
    'gentleduck/template',
    'project scaffolding templates',
    'component template generator',
    'monorepo starter template',
    'TypeScript UI library',
    'Next.js UI components',
    'React Server Components',
    'accessible React components',
    'open source React ecosystem',
    'design system for React',
    'UI toolkit for developers',
  ],
  manifest: `/site.webmanifest`,
  metadataBase: new URL(
    siteConfig.url.startsWith('http') ? siteConfig.url : `https://${process.env.VERCEL_URL ?? 'localhost:3000'}`,
  ),
  openGraph: {
    description: siteConfig.description,
    images: [
      {
        url: `/og?title=${encodeURIComponent(siteConfig.name)}&description=${encodeURIComponent(siteConfig.title)}`,
        width: 1400,
        height: 628,
        alt: siteConfig.name,
        type: 'image/png',
      },
    ],
    locale: 'en_US',
    siteName: siteConfig.name,
    title: siteConfig.name,
    type: 'website',
    url: siteConfig.url,
  },
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.name}`,
  },
  twitter: {
    card: 'summary_large_image',
    creator: '@gentleduck',
    description: siteConfig.description,
    images: [
      {
        url: `/og?title=${encodeURIComponent(siteConfig.name)}&description=${encodeURIComponent(siteConfig.title)}`,
        width: 1400,
        height: 628,
        alt: siteConfig.name,
      },
    ],
    title: siteConfig.name,
  },
}

export const SLUG_METADATA = (doc: { title: string; description: string; slug: string }): Metadata => {
  const ogUrl = `/og?title=${encodeURIComponent(doc.title)}&description=${encodeURIComponent(doc.description)}`
  return {
    ...METADATA,
    alternates: {
      canonical: absoluteUrl(doc.slug),
    },
    description: doc.description,
    openGraph: {
      ...METADATA.openGraph,
      description: doc.description,
      images: [{ url: ogUrl, width: 1400, height: 628, alt: doc.title, type: 'image/png' }],
      title: doc.title,
      type: 'article',
      url: absoluteUrl(doc.slug),
    },
    title: doc.title,
    twitter: {
      ...METADATA.twitter,
      description: doc.description,
      images: [{ url: ogUrl, width: 1400, height: 628, alt: doc.title }],
      title: doc.title,
    },
  }
}
