import {
  Box,
  Calendar,
  Command,
  Database,
  FileCode2,
  ImageIcon,
  Keyboard,
  KeyRound,
  LayoutGrid,
  Library,
  Link2,
  Palette,
  ScrollText,
  Sparkles,
  Terminal,
  Upload,
} from 'lucide-react'

export const navItems = [
  {
    title: 'Packages',
    href: '/duck-ui',
    description: 'Core packages that ship together and scale with your app.',
    items: [
      {
        title: '@gentleduck/ui',
        href: '/duck-ui',
        description: 'Production-ready UI components, blocks, and layouts.',
        icon: LayoutGrid,
        color: '#06b6d4',
      },
      {
        title: '@gentleduck/primitives',
        href: '/duck-primitives',
        description: 'Accessible headless primitives for design systems.',
        icon: Box,
        color: '#8b5cf6',
      },
      {
        title: '@gentleduck/cli',
        href: '/duck-cli',
        description: 'CLI for installing and generating UI assets.',
        icon: Terminal,
        color: '#22c55e',
      },
      {
        title: '@gentleduck/calendar',
        href: '/duck-calendar',
        description: 'Headless calendar engine with date adapters.',
        icon: Calendar,
        color: '#f97316',
      },
      {
        title: '@gentleduck/hooks',
        href: '/duck-hooks',
        description: 'Reusable React hooks for UI workflows.',
        icon: Link2,
        color: '#0ea5e9',
      },
      {
        title: '@gentleduck/variants',
        href: '/duck-variants',
        description: 'Type-safe variant builder for component APIs.',
        icon: Palette,
        color: '#ec4899',
      },
      {
        title: '@gentleduck/libs',
        href: '/duck-libs',
        description: 'Composable utility helpers for the ecosystem.',
        icon: Library,
        color: '#f59e0b',
      },
      {
        title: '@gentleduck/vim',
        href: '/duck-vim',
        description: 'Framework-agnostic keyboard command engine.',
        icon: Keyboard,
        color: '#ef4444',
      },
      {
        title: '@gentleduck/motion',
        href: '/duck-motion',
        description: 'Enter/exit animations and mount/unmount transitions.',
        icon: Sparkles,
        color: '#a855f7',
        status: 'wip',
      },
      {
        title: '@gentleduck/lazy',
        href: '/duck-lazy',
        description: 'Lazy-loading utilities for images and components.',
        icon: ImageIcon,
        color: '#14b8a6',
      },
      {
        title: '@gentleduck/state',
        href: '/duck-state',
        description: 'Atom-based state management for React.',
        icon: Database,
        color: '#6366f1',
        status: 'experimental',
      },
      {
        title: '@gentleduck/shortcut',
        href: '/duck-shortcut',
        description: 'Keyboard shortcut hooks for power-user interfaces.',
        icon: Command,
        color: '#f43f5e',
        status: 'deprecated',
      },
      {
        title: '@gentleduck/ttlog',
        href: '/duck-ttlog',
        description: 'Structured, type-safe terminal logging with pluggable transports.',
        icon: ScrollText,
        color: '#84cc16',
      },
      {
        title: '@gentleduck/upload',
        href: '/duck-upload',
        description: 'File upload engine with multipart, chunked, and presigned URL support.',
        icon: Upload,
        color: '#3b82f6',
        status: 'wip',
      },
      {
        title: '@gentleduck/iam',
        href: '/duck-iam',
        description: 'Identity and access management — roles, permissions, and policy enforcement.',
        icon: KeyRound,
        color: '#eab308',
      },
      {
        title: '@gentleduck/template',
        href: '/duck-template',
        description: 'Project and component scaffolding templates for the gentleduck ecosystem.',
        icon: FileCode2,
        color: '#d946ef',
      },
    ],
  },
  { href: '/skills', title: 'Skills' },
  { href: '/mcp', title: 'MCP' },
]
