import type { RegistryEntry } from '../registry-schema'

export const registrySidebar: RegistryEntry[] = [
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-01',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-01',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-02',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-02',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-03',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator'],
    root_folder: 'sidebar/sidebar-03',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-04',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator'],
    root_folder: 'sidebar/sidebar-04',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-05',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator'],
    root_folder: 'sidebar/sidebar-05',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-06',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'collapsible'],
    root_folder: 'sidebar/sidebar-06',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-07',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'collapsible', 'avatar', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-07',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-08',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'collapsible', 'avatar', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-08',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-09',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'avatar', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-09',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-10',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'collapsible', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-10',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-11',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator'],
    root_folder: 'sidebar/sidebar-11',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-12',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'calendar', 'collapsible', 'avatar', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-12',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-13',
    registryDependencies: ['sidebar', 'breadcrumb', 'button', 'dialog'],
    root_folder: 'sidebar/sidebar-13',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-14',
    registryDependencies: ['sidebar', 'breadcrumb'],
    root_folder: 'sidebar/sidebar-14',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-15',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'calendar', 'collapsible', 'avatar', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-15',
    type: 'registry:block',
  },
  {
    categories: ['sidebar'],
    files: [],
    name: 'sidebar-16',
    registryDependencies: ['sidebar', 'breadcrumb', 'separator', 'button', 'collapsible', 'avatar', 'dropdown-menu'],
    root_folder: 'sidebar/sidebar-16',
    type: 'registry:block',
  },
]
