import type {
  IRegistryBuildComponentIndexEntryOptions,
  IRegistryBuildComponentIndexImportOptions,
} from './component-index.types'

export const NEXTJS_COMPONENT_INDEX_HEADER = `// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build
// Do not edit this file directly.
import * as React from "react"

let dynamic: any
try { dynamic = (await import("next/dynamic.js")).default } catch { dynamic = () => () => null }
`

export function createNextjsComponentImport(options: IRegistryBuildComponentIndexImportOptions) {
  // JSON.stringify on componentPath guarantees the path can't break out of the string literal.
  return `const ${options.id} = dynamic(() => import(${JSON.stringify(options.componentPath)}), { ssr: ${String(
    options.ssr,
  )} })\n`
}

export function createComponentIndexEntry(options: IRegistryBuildComponentIndexEntryOptions) {
  const item = options.item

  // Every user-controlled string is run through JSON.stringify so a hostile registry
  // entry (e.g. `description: '"; process.exit(); //'`) cannot escape the literal and
  // inject executable code into the consumer's bundle.
  return `
  ${JSON.stringify(item.name)}: {
    name: ${JSON.stringify(item.name)},
    description: ${JSON.stringify(item.description ?? '')},
    type: ${JSON.stringify(item.type)},
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: ${JSON.stringify(item.files, null, 2)},
    component: ${options.id},
    source: ${JSON.stringify(item.source ?? '')},
    categories: ${JSON.stringify(item.categories ?? [])},
    root_folder: ${JSON.stringify(item.root_folder)},
  },`
}
