export const VITE_COMPONENT_INDEX_HEADER = `// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build
// Do not edit this file directly.
import * as React from "react"
`

export function createViteComponentImport(options: { componentPath: string; id: string }) {
  // JSON.stringify on componentPath guarantees the path can't break out of the string literal.
  return `const ${options.id} = React.lazy(() => import(${JSON.stringify(options.componentPath)}))\n`
}
