export type { IDocsVeliteConfigOptions } from './config'
export { createDocsVeliteConfig, docsVeliteConfig } from './config'
export { rehypeMetadataPlugin, rhypeMetadataPlugin } from './plugins/metadata-plugin'
export { rehypeComponent } from './plugins/rehype-component'
export { rehypeMermaid } from './plugins/rehype-mermaid'
export { rehypeNpmCommand } from './plugins/rehype-npm-command'
export { rehypePreBlockSource } from './plugins/rehype-pre-block-source'
export { rehypeTitle } from './plugins/rehype-title'
export { cleanTocItems } from './utils'
