'use client'

export { DialogClose as SheetClose, DialogClose as Close } from '../dialog/close'
export { DialogContent as SheetContent, DialogContent as Content } from '../dialog/content'
export { DialogDescription as SheetDescription, DialogDescription as Description } from '../dialog/description'
export { createDialogScope as createSheetScope, Dialog as Sheet, Dialog as Root } from '../dialog/dialog'
export { DialogOverlay as SheetOverlay, DialogOverlay as Overlay } from '../dialog/overlay'
export { DialogPortal as SheetPortal, DialogPortal as Portal } from '../dialog/portal'
export { DialogTitle as SheetTitle, DialogTitle as Title } from '../dialog/title'
export { DialogTrigger as SheetTrigger, DialogTrigger as Trigger } from '../dialog/trigger'
export type { ISheet } from './sheet.types'
