'use client'

export type { IDialogCloseProps as SheetCloseProps } from '../dialog/close'
export { DialogClose as SheetClose, DialogClose as Close } from '../dialog/close'
export type { IDialogContentProps as SheetContentProps } from '../dialog/content'
export { DialogContent as SheetContent, DialogContent as Content } from '../dialog/content'
export type { IDialogDescriptionProps as SheetDescriptionProps } from '../dialog/description'
export { DialogDescription as SheetDescription, DialogDescription as Description } from '../dialog/description'
export type { IDialogProps as SheetProps } from '../dialog/dialog'
export { createDialogScope as createSheetScope, Dialog as Sheet, Dialog as Root } from '../dialog/dialog'
export type { IDialogOverlayProps as SheetOverlayProps } from '../dialog/overlay'
export { DialogOverlay as SheetOverlay, DialogOverlay as Overlay } from '../dialog/overlay'
export type { IDialogPortalProps as SheetPortalProps } from '../dialog/portal'
export { DialogPortal as SheetPortal, DialogPortal as Portal } from '../dialog/portal'
export type { IDialogTitleProps as SheetTitleProps } from '../dialog/title'
export { DialogTitle as SheetTitle, DialogTitle as Title } from '../dialog/title'
export type { IDialogTriggerProps as SheetTriggerProps } from '../dialog/trigger'
export { DialogTrigger as SheetTrigger, DialogTrigger as Trigger } from '../dialog/trigger'
