'use client'

export type { DialogCloseProps as SheetCloseProps } from '../dialog/close'
export { DialogClose as SheetClose, DialogClose as Close } from '../dialog/close'
export type { DialogContentProps as SheetContentProps } from '../dialog/content'
export { DialogContent as SheetContent, DialogContent as Content } from '../dialog/content'
export type { DialogDescriptionProps as SheetDescriptionProps } from '../dialog/description'
export { DialogDescription as SheetDescription, DialogDescription as Description } from '../dialog/description'
export type { DialogProps as SheetProps } from '../dialog/dialog'
export { createDialogScope as createSheetScope, Dialog as Sheet, Dialog as Root } from '../dialog/dialog'
export type { DialogOverlayProps as SheetOverlayProps } from '../dialog/overlay'
export { DialogOverlay as SheetOverlay, DialogOverlay as Overlay } from '../dialog/overlay'
export type { DialogPortalProps as SheetPortalProps } from '../dialog/portal'
export { DialogPortal as SheetPortal, DialogPortal as Portal } from '../dialog/portal'
export type { DialogTitleProps as SheetTitleProps } from '../dialog/title'
export { DialogTitle as SheetTitle, DialogTitle as Title } from '../dialog/title'
export type { DialogTriggerProps as SheetTriggerProps } from '../dialog/trigger'
export { DialogTrigger as SheetTrigger, DialogTrigger as Trigger } from '../dialog/trigger'
