import type { RegistryEntry } from '../registry-schema'

export const registryUi: RegistryEntry[] = [
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'accordion',
    root_folder: 'accordion',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'alert',
    root_folder: 'alert',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'alert-dialog',
    registryDependencies: ['button'],
    root_folder: 'alert-dialog',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'aspect-ratio',
    root_folder: 'aspect-ratio',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'avatar',
    root_folder: 'avatar',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'badge',
    root_folder: 'badge',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'breadcrumb',
    root_folder: 'breadcrumb',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/variants', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'button',
    root_folder: 'button',
    type: 'registry:ui',
  },
  {
    dependencies: ['react-day-picker', '@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'calendar',
    registryDependencies: ['button'],
    root_folder: 'calendar',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'card',
    root_folder: 'card',
    type: 'registry:ui',
  },
  {
    dependencies: ['embla-carousel-react', '@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'carousel',
    registryDependencies: ['button'],
    root_folder: 'carousel',
    type: 'registry:ui',
  },
  {
    dependencies: ['recharts', '@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'chart',
    root_folder: 'chart',
    type: 'registry:ui',
  },

  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/motion', '@gentleduck/libs'],
    files: [],
    name: 'checkbox',
    registryDependencies: ['label'],
    root_folder: 'checkbox',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'collapsible',
    registryDependencies: ['button'],
    root_folder: 'collapsible',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/vim', '@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'command',
    registryDependencies: ['scroll-area', 'dialog'],
    root_folder: 'command',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'combobox',
    registryDependencies: ['badge', 'button', 'checkbox', 'command', 'popover', 'separator'],
    root_folder: 'combobox',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'context-menu',
    registryDependencies: [],
    root_folder: 'context-menu',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/hooks', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'dialog',
    registryDependencies: ['drawer'],
    root_folder: 'dialog',
    type: 'registry:ui',
  },
  {
    dependencies: ['vaul', '@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'drawer',
    root_folder: 'drawer',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives'],
    files: [],
    name: 'direction',
    root_folder: 'direction',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'dropdown-menu',
    registryDependencies: [],
    root_folder: 'dropdown-menu',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'navigation-menu',
    registryDependencies: [],
    root_folder: 'navigation-menu',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives', '@gentleduck/variants'],
    files: [],
    name: 'hover-card',
    registryDependencies: ['button'],
    root_folder: 'hover-card',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'input',
    root_folder: 'input',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'input-otp',
    root_folder: 'input-otp',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'label',
    root_folder: 'label',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/motion', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'menubar',
    registryDependencies: [],
    root_folder: 'menubar',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'pagination',
    registryDependencies: ['button'],
    root_folder: 'pagination',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'popover',
    root_folder: 'popover',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'progress',
    root_folder: 'progress',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'radio-group',
    registryDependencies: ['label'],
    root_folder: 'radio-group',
    type: 'registry:ui',
  },
  {
    dependencies: ['react-resizable-panels', '@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'resizable',
    root_folder: 'resizable',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'scroll-area',
    root_folder: 'scroll-area',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', 'lucide-react'],
    files: [],
    name: 'select',
    registryDependencies: [],
    root_folder: 'select',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'separator',
    root_folder: 'separator',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', '@gentleduck/variants', 'lucide-react'],
    files: [],
    name: 'sheet',
    root_folder: 'sheet',
    type: 'registry:ui',
  },
  {
    dependencies: [
      '@gentleduck/hooks',
      '@gentleduck/libs',
      '@gentleduck/primitives',
      '@gentleduck/variants',
      'lucide-react',
    ],
    files: [],
    name: 'sidebar',
    registryDependencies: ['button', 'input', 'separator', 'sheet', 'skeleton', 'tooltip'],
    root_folder: 'sidebar',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'skeleton',
    root_folder: 'skeleton',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs'],
    files: [],
    name: 'slider',
    root_folder: 'slider',
    type: 'registry:ui',
  },
  {
    dependencies: ['sonner', 'next-themes', '@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'sonner',
    registryDependencies: ['button', 'progress'],
    root_folder: 'sonner',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/primitives', '@gentleduck/libs', '@gentleduck/motion'],
    files: [],
    name: 'switch',
    root_folder: 'switch',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'table',
    root_folder: 'table',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'tabs',
    registryDependencies: [],
    root_folder: 'tabs',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'textarea',
    root_folder: 'textarea',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'toggle',
    registryDependencies: [],
    root_folder: 'toggle',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/variants', '@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'toggle-group',
    registryDependencies: ['toggle'],
    root_folder: 'toggle-group',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'tooltip',
    root_folder: 'tooltip',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/motion'],
    files: [],
    name: 'typography',
    root_folder: 'typography',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/variants', '@gentleduck/primitives'],
    files: [],
    name: 'button-group',
    registryDependencies: ['button', 'separator'],
    root_folder: 'button-group',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives'],
    files: [],
    name: 'kbd',
    root_folder: 'kbd',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/variants', '@gentleduck/primitives'],
    files: [],
    name: 'empty',
    root_folder: 'empty',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/variants', '@gentleduck/primitives'],
    files: [],
    name: 'field',
    registryDependencies: ['label', 'separator'],
    root_folder: 'field',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives', '@gentleduck/variants'],
    files: [],
    name: 'item',
    registryDependencies: ['separator'],
    root_folder: 'item',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/variants', '@gentleduck/primitives'],
    files: [],
    name: 'input-group',
    registryDependencies: ['button', 'input', 'textarea'],
    root_folder: 'input-group',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives', 'react-hook-form', 'sonner', 'lucide-react'],
    files: [],
    name: 'json-editor',
    registryDependencies: ['alert-dialog', 'button', 'popover', 'field', 'sheet'],
    root_folder: 'json-editor',
    type: 'registry:ui',
  },
  {
    dependencies: ['@gentleduck/libs', '@gentleduck/primitives', 'lucide-react'],
    files: [],
    name: 'preview-panel',
    registryDependencies: ['badge', 'button', 'button-group', 'dialog', 'separator', 'tooltip'],
    root_folder: 'preview-panel',
    type: 'registry:ui',
  },
]
