import type { IDocsConfig } from '@gentleduck/docs'

export const DuckUiConfig: IDocsConfig = {
  mainNav: [],
  chartsNav: [],
  sidebarNav: [
    {
      href: '/duck-ui/introduction',
      title: 'Getting Started',
      items: [
        { href: '/duck-ui/introduction', title: 'Introduction', items: [] },
        { href: '/duck-ui/theming', title: 'Theming', items: [] },
        { href: '/duck-ui/javascript', title: 'JavaScript', items: [] },
        { href: '/duck-ui/faqs', title: 'FAQs', items: [] },
      ],
    },
    {
      title: 'Installation',
      items: [
        { href: '/duck-ui/installation', title: 'Overview', items: [] },
        { href: '/duck-ui/installation/next', title: 'Next.js', items: [] },
        { href: '/duck-ui/installation/vite', title: 'Vite', items: [] },
        { href: '/duck-ui/installation/astro', title: 'Astro', items: [] },
        { href: '/duck-ui/installation/laravel', title: 'Laravel', items: [] },
        { href: '/duck-ui/installation/react-router', title: 'React Router', items: [] },
        { href: '/duck-ui/installation/tanstack', title: 'TanStack Start', items: [] },
        { href: '/duck-ui/installation/tanstack-router', title: 'TanStack Router', items: [] },
        { href: '/duck-ui/installation/manual', title: 'Manual', items: [] },
        { href: '/duck-ui/installation/monorepo', title: 'Monorepo', items: [] },
      ],
    },

    {
      title: 'Components',
      items: [
        { href: '/duck-ui/components/accordion', title: 'Accordion', items: [] },
        { href: '/duck-ui/components/alert', title: 'Alert', items: [] },
        { href: '/duck-ui/components/alert-dialog', title: 'Alert Dialog', items: [] },
        { href: '/duck-ui/components/aspect-ratio', title: 'Aspect Ratio', items: [] },
        { href: '/duck-ui/components/avatar', title: 'Avatar', items: [] },
        { href: '/duck-ui/components/badge', title: 'Badge', items: [] },
        { href: '/duck-ui/components/breadcrumb', title: 'Breadcrumb', items: [] },
        { href: '/duck-ui/components/button', title: 'Button', items: [] },
        { href: '/duck-ui/components/button-group', title: 'Button Group', items: [] },
        { href: '/duck-ui/components/calendar', title: 'Calendar', items: [] },
        { href: '/duck-ui/components/card', title: 'Card', items: [] },
        { href: '/duck-ui/components/carousel', title: 'Carousel', items: [] },
        { href: '/duck-ui/components/chart', title: 'Chart', items: [] },
        { href: '/duck-ui/components/checkbox', title: 'Checkbox', items: [] },
        { href: '/duck-ui/components/collapsible', title: 'Collapsible', items: [] },
        { href: '/duck-ui/components/combobox', title: 'Combobox', items: [] },
        { href: '/duck-ui/components/command', title: 'Command', items: [] },
        { href: '/duck-ui/components/context-menu', title: 'Context Menu', items: [] },
        { href: '/duck-ui/components/data-table', title: 'Data Table', items: [] },
        { href: '/duck-ui/components/date-picker', title: 'Date Picker', items: [] },
        { href: '/duck-ui/components/dialog', title: 'Dialog', items: [] },
        { href: '/duck-ui/components/drawer', title: 'Drawer', items: [] },
        { href: '/duck-ui/components/dropdown-menu', title: 'Dropdown Menu', items: [] },
        { href: '/duck-ui/components/empty', title: 'Empty', items: [] },
        { href: '/duck-ui/components/field', title: 'Field', items: [] },
        { href: '/duck-ui/components/hover-card', title: 'Hover Card', items: [] },
        { href: '/duck-ui/components/input', title: 'Input', items: [] },
        { href: '/duck-ui/components/input-group', title: 'Input Group', items: [] },
        { href: '/duck-ui/components/input-otp', title: 'Input OTP', items: [] },
        { href: '/duck-ui/components/json-editor', title: 'JSON Editor', items: [] },
        { href: '/duck-ui/components/kbd', title: 'Kbd', items: [] },
        { href: '/duck-ui/components/label', title: 'Label', items: [] },
        { href: '/duck-ui/components/menubar', title: 'Menubar', items: [] },
        { href: '/duck-ui/components/navigation-menu', title: 'Navigation Menu', items: [] },
        { href: '/duck-ui/components/pagination', title: 'Pagination', items: [] },
        { href: '/duck-ui/components/popover', title: 'Popover', items: [] },
        { href: '/duck-ui/components/preview-panel', title: 'Preview Panel', items: [] },
        { href: '/duck-ui/components/progress', title: 'Progress', items: [] },
        { href: '/duck-ui/components/radio-group', title: 'Radio Group', items: [] },
        { href: '/duck-ui/components/resizable', title: 'Resizable', items: [] },
        { href: '/duck-ui/components/scroll-area', title: 'Scroll Area', items: [] },
        { href: '/duck-ui/components/select', title: 'Select', items: [] },
        { href: '/duck-ui/components/separator', title: 'Separator', items: [] },
        { href: '/duck-ui/components/sheet', title: 'Sheet', items: [] },
        { href: '/duck-ui/components/sidebar', title: 'Sidebar', items: [] },
        { href: '/duck-ui/components/skeleton', title: 'Skeleton', items: [] },
        { href: '/duck-ui/components/slider', title: 'Slider', items: [] },
        { href: '/duck-ui/components/sonner', title: 'Sonner', items: [] },
        { href: '/duck-ui/components/switch', title: 'Switch', items: [] },
        { href: '/duck-ui/components/table', title: 'Table', items: [] },
        { href: '/duck-ui/components/tabs', title: 'Tabs', items: [] },
        { href: '/duck-ui/components/textarea', title: 'Text Area', items: [] },
        { href: '/duck-ui/components/toggle', title: 'Toggle', items: [] },
        { href: '/duck-ui/components/toggle-group', title: 'Toggle Group', items: [] },
        { href: '/duck-ui/components/tooltip', title: 'Tooltip', items: [] },
        { href: '/duck-ui/components/typography', title: 'Typography', items: [] },
      ],
    },

    {
      title: 'Integrations',
      items: [
        { href: '/duck-ui/components/react-hook-form', title: 'React Hook Form', items: [] },
        { href: '/duck-ui/components/tanstack-form', title: 'TanStack Form', items: [] },
      ],
    },
  ],
}
