import type { IDocsConfig } from '@gentleduck/docs'

export const DuckPrimitivesConfig: IDocsConfig = {
  mainNav: [],
  chartsNav: [],
  sidebarNav: [
    {
      href: '/duck-primitives/introduction',
      title: 'Getting Started',
      items: [
        { href: '/duck-primitives/introduction', title: 'Introduction', items: [] },
        { href: '/duck-primitives/getting-started', title: 'Installation', items: [] },
        { href: '/duck-primitives/concepts', title: 'Core Concepts', items: [] },
      ],
    },
    {
      title: 'Guides',
      items: [
        { href: '/duck-primitives/guides', title: 'Overview', items: [] },
        { href: '/duck-primitives/guides/composition', title: 'Composition', items: [] },
        { href: '/duck-primitives/guides/styling', title: 'Styling', items: [] },
        { href: '/duck-primitives/guides/animation', title: 'Animation', items: [] },
        { href: '/duck-primitives/guides/accessibility', title: 'Accessibility', items: [] },
      ],
    },
    {
      title: 'Primitives',
      items: [
        { href: '/duck-primitives/api/accordion', title: 'Accordion', items: [] },
        { href: '/duck-primitives/api/alert-dialog', title: 'Alert Dialog', items: [] },
        { href: '/duck-primitives/api/avatar', title: 'Avatar', items: [] },
        { href: '/duck-primitives/api/calendar', title: 'Calendar', items: [] },
        { href: '/duck-primitives/api/command', title: 'Command', items: [] },
        { href: '/duck-primitives/api/context-menu', title: 'Context Menu', items: [] },
        { href: '/duck-primitives/api/dialog', title: 'Dialog', items: [] },
        { href: '/duck-primitives/api/dropdown-menu', title: 'Dropdown Menu', items: [] },
        { href: '/duck-primitives/api/hover-card', title: 'Hover Card', items: [] },
        { href: '/duck-primitives/api/input-otp', title: 'Input OTP', items: [] },
        { href: '/duck-primitives/api/menu', title: 'Menu', items: [] },
        { href: '/duck-primitives/api/menubar', title: 'Menubar', items: [] },
        { href: '/duck-primitives/api/navigation-menu', title: 'Navigation Menu', items: [] },
        { href: '/duck-primitives/api/pagination', title: 'Pagination', items: [] },
        { href: '/duck-primitives/api/popover', title: 'Popover', items: [] },
        { href: '/duck-primitives/api/progress', title: 'Progress', items: [] },
        { href: '/duck-primitives/api/radio-group', title: 'Radio Group', items: [] },
        { href: '/duck-primitives/api/select', title: 'Select', items: [] },
        { href: '/duck-primitives/api/sheet', title: 'Sheet', items: [] },
        { href: '/duck-primitives/api/slider', title: 'Slider', items: [] },
        { href: '/duck-primitives/api/toggle', title: 'Toggle', items: [] },
        { href: '/duck-primitives/api/toggle-group', title: 'Toggle Group', items: [] },
        { href: '/duck-primitives/api/tooltip', title: 'Tooltip', items: [] },
      ],
    },
    {
      title: 'Internals',
      items: [
        { href: '/duck-primitives/api/arrow', title: 'Arrow', items: [] },
        { href: '/duck-primitives/api/checkers', title: 'Checkers', items: [] },
        { href: '/duck-primitives/api/direction', title: 'Direction', items: [] },
        { href: '/duck-primitives/api/dismissable-layer', title: 'Dismissable Layer', items: [] },
        { href: '/duck-primitives/api/focus-scope', title: 'Focus Scope', items: [] },
        { href: '/duck-primitives/api/mount', title: 'Mount', items: [] },
        { href: '/duck-primitives/api/popper', title: 'Popper', items: [] },
        { href: '/duck-primitives/api/portal', title: 'Portal', items: [] },
        { href: '/duck-primitives/api/presence', title: 'Presence', items: [] },
        { href: '/duck-primitives/api/primitive-elements', title: 'Primitive Elements', items: [] },
        { href: '/duck-primitives/api/roving-focus', title: 'Roving Focus', items: [] },
        { href: '/duck-primitives/api/slot', title: 'Slot', items: [] },
        { href: '/duck-primitives/api/visibility-hidden', title: 'Visibility Hidden', items: [] },
      ],
    },
    {
      title: 'Resources',
      items: [
        { href: '/duck-primitives/api', title: 'API Reference', items: [] },
        { href: '/duck-primitives/benchmarks', title: 'Benchmarks', items: [] },
      ],
    },
    {
      title: 'Course',
      items: [
        { href: '/duck-primitives/course', title: 'Overview', items: [] },
        { href: '/duck-primitives/course/01-why-primitives', title: 'Why Primitives', items: [] },
        { href: '/duck-primitives/course/02-first-dialog', title: 'Your First Dialog', items: [] },
        { href: '/duck-primitives/course/03-as-child', title: 'The asChild Pattern', items: [] },
        { href: '/duck-primitives/course/04-popover', title: 'Popover and Positioning', items: [] },
        { href: '/duck-primitives/course/05-menus', title: 'Menus and Selection', items: [] },
        { href: '/duck-primitives/course/06-animation', title: 'Animation with Presence', items: [] },
        { href: '/duck-primitives/course/07-accessibility', title: 'Accessibility Deep Dive', items: [] },
        { href: '/duck-primitives/course/08-design-system', title: 'Building a Design System', items: [] },
        { href: '/duck-primitives/course/09-testing-quality', title: 'Testing and Quality Gates', items: [] },
        { href: '/duck-primitives/course/10-operations-migration', title: 'Operations and Migration', items: [] },
      ],
    },
  ],
}
