export type { Attendee, CalendarEvent, CalendarView, EventCategory, FilterMode } from './calendar-1.types'

import type { CalendarEvent, EventCategory } from './calendar-1.types'

export const CATEGORY_COLORS: Record<EventCategory, { bg: string; dot: string; text: string; border: string }> = {
  standup: {
    bg: 'bg-sky-50 dark:bg-sky-500/15',
    dot: 'bg-sky-500',
    text: 'text-sky-700 dark:text-sky-300',
    border: 'border-sky-400',
  },
  'one-on-one': {
    bg: 'bg-purple-50 dark:bg-purple-500/15',
    dot: 'bg-purple-500',
    text: 'text-purple-700 dark:text-purple-300',
    border: 'border-purple-400',
  },
  'deep-work': {
    bg: 'bg-blue-50 dark:bg-blue-500/15',
    dot: 'bg-blue-500',
    text: 'text-blue-700 dark:text-blue-300',
    border: 'border-blue-400',
  },
  design: {
    bg: 'bg-fuchsia-50 dark:bg-fuchsia-500/15',
    dot: 'bg-fuchsia-500',
    text: 'text-fuchsia-700 dark:text-fuchsia-300',
    border: 'border-fuchsia-400',
  },
  'all-hands': {
    bg: 'bg-yellow-50 dark:bg-yellow-500/15',
    dot: 'bg-yellow-500',
    text: 'text-yellow-700 dark:text-yellow-300',
    border: 'border-yellow-400',
  },
  social: {
    bg: 'bg-orange-50 dark:bg-orange-500/15',
    dot: 'bg-orange-500',
    text: 'text-orange-700 dark:text-orange-300',
    border: 'border-orange-400',
  },
  external: {
    bg: 'bg-emerald-50 dark:bg-emerald-500/15',
    dot: 'bg-emerald-500',
    text: 'text-emerald-700 dark:text-emerald-300',
    border: 'border-emerald-400',
  },
  planning: {
    bg: 'bg-indigo-50 dark:bg-indigo-500/15',
    dot: 'bg-indigo-500',
    text: 'text-indigo-700 dark:text-indigo-300',
    border: 'border-indigo-400',
  },
  review: {
    bg: 'bg-rose-50 dark:bg-rose-500/15',
    dot: 'bg-rose-500',
    text: 'text-rose-700 dark:text-rose-300',
    border: 'border-rose-400',
  },
  personal: {
    bg: 'bg-teal-50 dark:bg-teal-500/15',
    dot: 'bg-teal-500',
    text: 'text-teal-700 dark:text-teal-300',
    border: 'border-teal-400',
  },
  other: {
    bg: 'bg-zinc-100 dark:bg-zinc-500/15',
    dot: 'bg-zinc-400',
    text: 'text-zinc-700 dark:text-zinc-300',
    border: 'border-zinc-400',
  },
}

export const CATEGORY_LABELS: Record<EventCategory, string> = {
  standup: 'Standup',
  'one-on-one': '1:1',
  'deep-work': 'Deep Work',
  design: 'Design',
  'all-hands': 'All Hands',
  social: 'Social',
  external: 'External',
  planning: 'Planning',
  review: 'Review',
  personal: 'Personal',
  other: 'Other',
}

const AVATARS = [
  'https://api.dicebear.com/9.x/avataaars/svg?seed=Olivia',
  'https://api.dicebear.com/9.x/avataaars/svg?seed=Alex',
  'https://api.dicebear.com/9.x/avataaars/svg?seed=Amelie',
  'https://api.dicebear.com/9.x/avataaars/svg?seed=Zahir',
  'https://api.dicebear.com/9.x/avataaars/svg?seed=Riley',
  'https://api.dicebear.com/9.x/avataaars/svg?seed=Sienna',
]

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: 'e01',
    title: 'Monday standup',
    date: '2024-12-30',
    time: '9:00 AM',
    timeValue: 540,
    category: 'standup',
    attendees: [
      { name: 'Sienna Hewitt', email: 'sienna@untitledui.com', avatar: AVATARS[5] },
      { name: 'Olivia Rhye', email: 'olivia@untitledui.com', avatar: AVATARS[0] },
    ],
  },
  {
    id: 'e02',
    title: 'Coffee with Alina',
    date: '2024-12-31',
    time: '11:30 AM',
    timeValue: 690,
    category: 'social',
    location: 'Blue Bottle Coffee',
    attendees: [{ name: 'Alina Torres', email: 'alina@untitledui.com', avatar: AVATARS[2] }],
  },
  {
    id: 'e03',
    title: 'Marketing site review',
    date: '2024-12-31',
    time: '2:30 PM',
    timeValue: 870,
    category: 'planning',
    link: 'https://meet.google.com/abc-defg-hij',
  },
  { id: 'e04', title: 'Monday standup', date: '2024-12-31', time: '9:00 AM', timeValue: 540, category: 'standup' },
  {
    id: 'e05',
    title: 'One-on-one with PM',
    date: '2025-01-02',
    time: '10:00 AM',
    timeValue: 600,
    category: 'one-on-one',
    attendees: [{ name: 'Alex Chen', email: 'alex@untitledui.com', avatar: AVATARS[1] }],
    link: 'https://zoom.us/j/123456',
    description: 'Weekly sync on product roadmap and Q1 priorities.',
  },
  {
    id: 'e06',
    title: 'All-hands meeting',
    date: '2025-01-02',
    time: '4:00 PM',
    timeValue: 960,
    category: 'all-hands',
    location: 'Main Conference Room',
    attendees: [
      { name: 'Sienna Hewitt', email: 'sienna@untitledui.com', avatar: AVATARS[5] },
      { name: 'Olivia Rhye', email: 'olivia@untitledui.com', avatar: AVATARS[0] },
      { name: 'Alex Chen', email: 'alex@untitledui.com', avatar: AVATARS[1] },
    ],
  },
  {
    id: 'e07',
    title: 'Dinner with Chloe',
    date: '2025-01-02',
    time: '6:30 PM',
    timeValue: 1110,
    category: 'external',
    starred: true,
    location: 'Nobu Downtown',
  },
  { id: 'e07b', title: 'Sprint retro', date: '2025-01-02', time: '2:00 PM', timeValue: 840, category: 'review' },
  { id: 'e08', title: 'Friday standup', date: '2025-01-03', time: '9:00 AM', timeValue: 540, category: 'standup' },
  {
    id: 'e09',
    title: 'House inspection',
    date: '2025-01-04',
    time: '10:30 AM',
    timeValue: 630,
    category: 'review',
    starred: true,
    location: '42 Oak Street',
  },
  {
    id: 'e10',
    title: "Ava's engagement party",
    date: '2025-01-05',
    time: '1:00 PM',
    timeValue: 780,
    category: 'social',
    starred: true,
    location: 'Rooftop Lounge',
  },
  { id: 'e11', title: 'Monday standup', date: '2025-01-06', time: '9:00 AM', timeValue: 540, category: 'standup' },
  {
    id: 'e12',
    title: 'Content planning',
    date: '2025-01-06',
    time: '11:00 AM',
    timeValue: 660,
    category: 'planning',
    link: 'https://www.figma.com/file/abc',
    attendees: [{ name: 'Amelie Duval', email: 'amelie@untitledui.com', avatar: AVATARS[2] }],
  },
  {
    id: 'e13',
    title: 'One-on-one with CTO',
    date: '2025-01-07',
    time: '10:00 AM',
    timeValue: 600,
    category: 'one-on-one',
    attendees: [{ name: 'Alex Chen', email: 'alex@untitledui.com', avatar: AVATARS[1] }],
  },
  {
    id: 'e14',
    title: 'Catch up w/ Alex',
    date: '2025-01-07',
    time: '2:30 PM',
    timeValue: 870,
    category: 'social',
    attendees: [{ name: 'Alex Chen', email: 'alex@untitledui.com', avatar: AVATARS[1] }],
    location: 'Cafe Luna',
  },
  {
    id: 'e15',
    title: 'Deep work',
    date: '2025-01-08',
    time: '9:00 AM',
    timeValue: 540,
    category: 'deep-work',
    description: 'Focus block - no meetings. Working on new component API.',
  },
  {
    id: 'e16',
    title: 'Design sync',
    date: '2025-01-08',
    time: '10:30 AM',
    timeValue: 630,
    category: 'design',
    link: 'https://www.figma.com/file/xyz',
    attendees: [
      { name: 'Olivia Rhye', email: 'olivia@untitledui.com', avatar: AVATARS[0] },
      { name: 'Riley Park', email: 'riley@untitledui.com', avatar: AVATARS[4] },
    ],
  },
  { id: 'e17', title: 'SEO planning', date: '2025-01-08', time: '1:30 PM', timeValue: 810, category: 'planning' },
  { id: 'e17b', title: 'API review', date: '2025-01-08', time: '3:00 PM', timeValue: 900, category: 'review' },
  { id: 'e17c', title: 'Team sync', date: '2025-01-08', time: '4:30 PM', timeValue: 990, category: 'all-hands' },
  {
    id: 'e18',
    title: 'Lunch with Jordan',
    date: '2025-01-09',
    time: '12:00 PM',
    timeValue: 720,
    category: 'social',
    starred: true,
    location: 'Sweetgreen',
    attendees: [{ name: 'Jordan Lee', email: 'jordan@external.com' }],
  },
  { id: 'e19', title: 'Friday standup', date: '2025-01-10', time: '9:00 AM', timeValue: 540, category: 'standup' },
  {
    id: 'e20',
    title: 'Olivia x Riley',
    date: '2025-01-10',
    time: '10:00 AM',
    timeValue: 600,
    category: 'one-on-one',
    attendees: [
      { name: 'Olivia Rhye', email: 'olivia@untitledui.com', avatar: AVATARS[0] },
      { name: 'Riley Park', email: 'riley@untitledui.com', avatar: AVATARS[4] },
    ],
  },
  {
    id: 'e21',
    title: 'Product demo',
    date: '2025-01-10',
    time: '1:30 PM',
    timeValue: 810,
    category: 'all-hands',
    link: 'https://meet.google.com/demo-123',
    attendees: [
      { name: 'Sienna Hewitt', email: 'sienna@untitledui.com', avatar: AVATARS[5] },
      { name: 'Alex Chen', email: 'alex@untitledui.com', avatar: AVATARS[1] },
      { name: 'Amelie Duval', email: 'amelie@untitledui.com', avatar: AVATARS[2] },
    ],
  },
  {
    id: 'e22',
    title: 'House inspection',
    date: '2025-01-11',
    time: '10:00 AM',
    timeValue: 600,
    category: 'review',
    starred: true,
  },
  {
    id: 'e23',
    title: "Ava's engagement party",
    date: '2025-01-12',
    time: '1:00 PM',
    timeValue: 780,
    category: 'social',
    starred: true,
  },
  { id: 'e24', title: 'Monday standup', date: '2025-01-13', time: '9:00 AM', timeValue: 540, category: 'standup' },
  {
    id: 'e25',
    title: 'Team lunch',
    date: '2025-01-14',
    time: '12:15 PM',
    timeValue: 735,
    category: 'social',
    location: 'Craft Kitchen',
  },
  { id: 'e26', title: 'Product planning', date: '2025-01-15', time: '9:30 AM', timeValue: 570, category: 'planning' },
  {
    id: 'e27',
    title: "Amelie's first day",
    date: '2025-01-15',
    time: '10:00 AM',
    timeValue: 600,
    category: 'personal',
  },
  { id: 'e28', title: 'All-hands meeting', date: '2025-01-16', time: '4:00 PM', timeValue: 960, category: 'all-hands' },
  {
    id: 'e29',
    title: 'Coffee w/ Amelie',
    date: '2025-01-17',
    time: '9:30 AM',
    timeValue: 570,
    category: 'social',
    attendees: [{ name: 'Amelie Duval', email: 'amelie@untitledui.com', avatar: AVATARS[2] }],
  },
  {
    id: 'e30',
    title: 'Design feedback',
    date: '2025-01-17',
    time: '2:30 PM',
    timeValue: 870,
    category: 'design',
    link: 'https://www.figma.com/file/review',
  },
  { id: 'e31', title: 'Friday standup', date: '2025-01-17', time: '9:00 AM', timeValue: 540, category: 'standup' },
  {
    id: 'e32',
    title: 'Half marathon',
    date: '2025-01-18',
    time: '7:00 AM',
    timeValue: 420,
    category: 'personal',
    starred: true,
    location: 'Central Park',
  },
  { id: 'e33', title: 'Monday standup', date: '2025-01-20', time: '9:00 AM', timeValue: 540, category: 'standup' },
  { id: 'e34', title: 'Deep work', date: '2025-01-20', time: '9:15 AM', timeValue: 555, category: 'deep-work' },
  {
    id: 'e35',
    title: 'Quarterly review',
    date: '2025-01-21',
    time: '11:30 AM',
    timeValue: 690,
    category: 'review',
    attendees: [{ name: 'Sienna Hewitt', email: 'sienna@untitledui.com', avatar: AVATARS[5] }],
  },
  {
    id: 'e36',
    title: 'Lunch with Zahir',
    date: '2025-01-21',
    time: '1:00 PM',
    timeValue: 780,
    category: 'social',
    attendees: [{ name: 'Zahir Khan', email: 'zahir@untitledui.com', avatar: AVATARS[3] }],
    location: 'Ramen House',
  },
  {
    id: 'e37',
    title: 'Dinner with Chloe',
    date: '2025-01-21',
    time: '7:00 PM',
    timeValue: 1140,
    category: 'external',
    starred: true,
  },
  { id: 'e38', title: 'Deep work', date: '2025-01-22', time: '9:00 AM', timeValue: 540, category: 'deep-work' },
  { id: 'e39', title: 'Design sync', date: '2025-01-22', time: '2:30 PM', timeValue: 870, category: 'design' },
  { id: 'e40', title: 'Amelie coffee', date: '2025-01-23', time: '10:00 AM', timeValue: 600, category: 'social' },
  { id: 'e41', title: 'Friday standup', date: '2025-01-24', time: '9:00 AM', timeValue: 540, category: 'standup' },
  { id: 'e42', title: 'Accountant', date: '2025-01-24', time: '1:45 PM', timeValue: 825, category: 'personal' },
  {
    id: 'e43',
    title: 'Marketing site review',
    date: '2025-01-24',
    time: '2:30 PM',
    timeValue: 870,
    category: 'planning',
  },
  { id: 'e43b', title: 'Investor update', date: '2025-01-24', time: '4:00 PM', timeValue: 960, category: 'external' },
  { id: 'e44', title: 'Monday standup', date: '2025-01-27', time: '9:00 AM', timeValue: 540, category: 'standup' },
  { id: 'e45', title: 'Content planning', date: '2025-01-28', time: '11:00 AM', timeValue: 660, category: 'planning' },
  { id: 'e46', title: 'Lunch with Alina', date: '2025-01-28', time: '12:45 PM', timeValue: 765, category: 'social' },
  { id: 'e47', title: 'Product planning', date: '2025-01-29', time: '9:30 AM', timeValue: 570, category: 'planning' },
  { id: 'e48', title: 'All-hands meeting', date: '2025-01-30', time: '4:00 PM', timeValue: 960, category: 'all-hands' },
  {
    id: 'e49',
    title: 'Team dinner',
    date: '2025-01-30',
    time: '5:30 PM',
    timeValue: 1050,
    category: 'social',
    location: 'Tavern on the Green',
  },
  { id: 'e50', title: 'Friday standup', date: '2025-01-31', time: '9:00 AM', timeValue: 540, category: 'standup' },
  { id: 'e51', title: 'Monday standup', date: '2025-02-01', time: '9:00 AM', timeValue: 540, category: 'standup' },
]
