export type { IMotionConfigContextValue, IMotionProviderProps } from './motion-provider'
export { MotionProvider, useMotionConfig } from './motion-provider'
export type { IDuckMotion } from './presets/types'
export type { IReducedMotionFallback } from './react'
export { motionTransition, useDuckReducedMotion } from './react'
export { createStagger, getStaggerDelay, staggerChildren } from './stagger'
export { duckMotionDuration, duckMotionDurationMs, duckMotionEasing, duckMotionEasingCss } from './transitions'
export { AnimVariants, checkersStylePattern } from './variants'
