export type { IAlertDialogActionProps } from './action'
export { AlertDialogAction, AlertDialogAction as Action } from './action'
export type { IAlertDialogProps } from './alert-dialog'
// Short aliases for namespace-style imports
export { AlertDialog, AlertDialog as Root, createAlertDialogScope } from './alert-dialog'
export type { IAlertDialogCancelProps } from './cancel'
export { AlertDialogCancel, AlertDialogCancel as Cancel } from './cancel'
export type { IAlertDialogContentProps } from './content'
export { AlertDialogContent, AlertDialogContent as Content } from './content'
export type { IAlertDialogDescriptionProps } from './description'
export { AlertDialogDescription, AlertDialogDescription as Description } from './description'
export type { IAlertDialogOverlayProps } from './overlay'
export { AlertDialogOverlay, AlertDialogOverlay as Overlay } from './overlay'
export type { IAlertDialogPortalProps } from './portal'
export { AlertDialogPortal, AlertDialogPortal as Portal } from './portal'
export type { IAlertDialogTitleProps } from './title'
export { AlertDialogTitle, AlertDialogTitle as Title } from './title'
export type { IAlertDialogTriggerProps } from './trigger'
export { AlertDialogTrigger, AlertDialogTrigger as Trigger } from './trigger'
