export type { AlertDialogActionProps } from './action'
export { AlertDialogAction, AlertDialogAction as Action } from './action'
export type { AlertDialogProps } from './alert-dialog'
// Short aliases for namespace-style imports
export { AlertDialog, AlertDialog as Root, createAlertDialogScope } from './alert-dialog'
export type { AlertDialogCancelProps } from './cancel'
export { AlertDialogCancel, AlertDialogCancel as Cancel } from './cancel'
export type { AlertDialogContentProps } from './content'
export { AlertDialogContent, AlertDialogContent as Content } from './content'
export type { AlertDialogDescriptionProps } from './description'
export { AlertDialogDescription, AlertDialogDescription as Description } from './description'
export type { AlertDialogOverlayProps } from './overlay'
export { AlertDialogOverlay, AlertDialogOverlay as Overlay } from './overlay'
export type { AlertDialogPortalProps } from './portal'
export { AlertDialogPortal, AlertDialogPortal as Portal } from './portal'
export type { AlertDialogTitleProps } from './title'
export { AlertDialogTitle, AlertDialogTitle as Title } from './title'
export type { AlertDialogTriggerProps } from './trigger'
export { AlertDialogTrigger, AlertDialogTrigger as Trigger } from './trigger'
