// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Docs = Collections['docs']['schema']['_output']
export declare const docs: Docs[]

export type DuckCalendar = Collections['duckCalendar']['schema']['_output']
export declare const duckCalendar: DuckCalendar[]

export type DuckCli = Collections['duckCli']['schema']['_output']
export declare const duckCli: DuckCli[]

export type DuckGen = Collections['duckGen']['schema']['_output']
export declare const duckGen: DuckGen[]

export type DuckHooks = Collections['duckHooks']['schema']['_output']
export declare const duckHooks: DuckHooks[]

export type DuckIam = Collections['duckIam']['schema']['_output']
export declare const duckIam: DuckIam[]

export type DuckLazy = Collections['duckLazy']['schema']['_output']
export declare const duckLazy: DuckLazy[]

export type DuckLibs = Collections['duckLibs']['schema']['_output']
export declare const duckLibs: DuckLibs[]

export type DuckMotion = Collections['duckMotion']['schema']['_output']
export declare const duckMotion: DuckMotion[]

export type DuckPrimitives = Collections['duckPrimitives']['schema']['_output']
export declare const duckPrimitives: DuckPrimitives[]

export type DuckQuery = Collections['duckQuery']['schema']['_output']
export declare const duckQuery: DuckQuery[]

export type DuckRegistryBuild = Collections['duckRegistryBuild']['schema']['_output']
export declare const duckRegistryBuild: DuckRegistryBuild[]

export type DuckShortcut = Collections['duckShortcut']['schema']['_output']
export declare const duckShortcut: DuckShortcut[]

export type DuckState = Collections['duckState']['schema']['_output']
export declare const duckState: DuckState[]

export type DuckTemplate = Collections['duckTemplate']['schema']['_output']
export declare const duckTemplate: DuckTemplate[]

export type DuckTtest = Collections['duckTtest']['schema']['_output']
export declare const duckTtest: DuckTtest[]

export type DuckTtlog = Collections['duckTtlog']['schema']['_output']
export declare const duckTtlog: DuckTtlog[]

export type DuckUi = Collections['duckUi']['schema']['_output']
export declare const duckUi: DuckUi[]

export type DuckUpload = Collections['duckUpload']['schema']['_output']
export declare const duckUpload: DuckUpload[]

export type DuckVariants = Collections['duckVariants']['schema']['_output']
export declare const duckVariants: DuckVariants[]

export type DuckVim = Collections['duckVim']['schema']['_output']
export declare const duckVim: DuckVim[]

export type Www = Collections['www']['schema']['_output']
export declare const www: Www[]
