// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build
// Do not edit this file directly.
import * as React from "react"

let dynamic: any
try { dynamic = (await import("next/dynamic.js")).default } catch { dynamic = () => () => null }
const _Button = dynamic(() => import("@example/ui/button/button"), { ssr: false })
const _Basic = dynamic(() => import("@example/examples/button/basic"), { ssr: false })

export const Index: Record<string, any> = {
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
  {
    "path": "button/button.tsx",
    "type": "registry:ui"
  },
  {
    "path": "button/index.ts",
    "type": "registry:ui"
  }
],
    component: _Button,
    source: "/registry-ui/src/button",
    categories: [],
    root_folder: "button",
  },
  "basic": {
    name: "basic",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [
  {
    "path": "button/basic.tsx",
    "type": "registry:example"
  }
],
    component: _Basic,
    source: "/registry-examples/src/button",
    categories: [],
    root_folder: "button",
  },
}
