import { availableParallelism } from 'node:os'
import type {
  RegistryBuildConfig,
  RegistryBuildFramework,
  RegistryBuildPerformanceConfig,
  RegistryBuildSource,
  RegistryItemType,
  RegistryItemTypeMap,
  ResolvedRegistryBuildBranding,
  ResolvedRegistryBuildComponentIndex,
  ResolvedRegistryBuildCssTemplates,
  ResolvedRegistryBuildOutput,
  ResolvedRegistryBuildPerformanceConfig,
  ResolvedRegistryBuildPipelineConfig,
} from '../types'

export const DEFAULT_CONFIG_FILENAMES = [
  'registry-build.config.ts',
  'registry-build.config.mts',
  'registry-build.config.cts',
  'registry-build.config.js',
  'registry-build.config.mjs',
  'registry-build.config.cjs',
  'registry-build.config.json',
] as const

export const DEFAULT_SOURCE_GLOB = '**/*.{ts,tsx}'
export const DEFAULT_SOURCE_INDEX_STRATEGY = 'item' as const
export const DEFAULT_SOURCE_IGNORE = ['**/__test__/**', '**/*.test.*', '**/*.spec.*'] as const

export const DEFAULT_STRIP_VARIABLES = [] as const

export const DEFAULT_COMPONENT_INDEX_EXCLUDE_TYPES = [] as const

export const DEFAULT_COMPONENT_INDEX_FRAMEWORK: RegistryBuildFramework = 'nextjs'

export const DEFAULT_COMPONENT_INDEX_HEADER = `// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build
// Do not edit this file directly.
import * as React from "react"

let dynamic: any
try { dynamic = (await import("next/dynamic.js")).default } catch { dynamic = () => () => null }
`

export const DEFAULT_THEME_CSS_VAR_KEYS = [] as const

export const DEFAULT_THEME_NAMES = [] as const

export const DEFAULT_THEME_RADIUS = '0.5rem'

export const DEFAULT_OUTPUT: Omit<ResolvedRegistryBuildOutput, 'dir'> = {
  colorsDir: 'colors',
  componentIndexDir: '__ui_registry__',
  componentIndexFile: 'index.tsx',
  componentsDir: 'components',
  registryDir: 'public/r',
  themesCssFile: 'themes.css',
  themesDir: 'themes',
}

export const DEFAULT_COMPONENT_INDEX: Omit<ResolvedRegistryBuildComponentIndex, 'generator'> = {
  excludeTypes: [...DEFAULT_COMPONENT_INDEX_EXCLUDE_TYPES],
  framework: DEFAULT_COMPONENT_INDEX_FRAMEWORK,
  header: DEFAULT_COMPONENT_INDEX_HEADER,
  ssr: false,
}

export const DEFAULT_PIPELINE: ResolvedRegistryBuildPipelineConfig = {
  components: true,
  index: true,
}

export const DEFAULT_PERFORMANCE: ResolvedRegistryBuildPerformanceConfig = {
  cacheDir: '.registry-build',
  incremental: true,
  parallelism: Math.max(1, Math.min(availableParallelism(), 8)),
}

export const DEFAULT_BRANDING: ResolvedRegistryBuildBranding = {
  font: 'ANSI Shadow',
  name: '@gentleduck/registry-build',
}

export const DEFAULT_CSS_TEMPLATES: ResolvedRegistryBuildCssTemplates = {
  baseLayerRules: `@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}`,
  baseStyles: `@tailwind base;
@tailwind components;
@tailwind utilities;
  `,
}

export const DEFAULT_SCHEMA_ITEM_TYPES = [] as const

export function withRegistryBuildDefaults(config: RegistryBuildConfig): RegistryBuildConfig {
  const sourceEntries = Object.entries(config.sources ?? {}) as Array<[RegistryItemType, RegistryBuildSource]>

  return {
    ...config,
    componentIndex: {
      ...DEFAULT_COMPONENT_INDEX,
      ...config.componentIndex,
      excludeTypes: config.componentIndex?.excludeTypes ?? [...DEFAULT_COMPONENT_INDEX.excludeTypes],
    },
    cssTemplates: {
      ...DEFAULT_CSS_TEMPLATES,
      ...config.cssTemplates,
    },
    extensions: config.extensions ?? [],
    importMappings: {
      contentRewrites: config.importMappings?.contentRewrites ?? [],
      packageMappings: config.importMappings?.packageMappings ?? {},
    },
    output: config.output
      ? {
          ...DEFAULT_OUTPUT,
          ...config.output,
        }
      : undefined,
    performance: {
      ...DEFAULT_PERFORMANCE,
      ...config.performance,
    } satisfies RegistryBuildPerformanceConfig,
    pipeline: {
      ...DEFAULT_PIPELINE,
      ...config.pipeline,
    },
    registries: config.registries ?? {},
    registrySource: config.registrySource ?? 'inline',
    schema: {
      itemTypes: config.schema?.itemTypes ?? [...DEFAULT_SCHEMA_ITEM_TYPES],
    },
    sources: Object.fromEntries(
      sourceEntries.map(([type, source]) => [
        type,
        {
          ...source,
          glob: source.glob ?? DEFAULT_SOURCE_GLOB,
          ignore: source.ignore ?? [...DEFAULT_SOURCE_IGNORE],
          indexStrategy: source.indexStrategy ?? DEFAULT_SOURCE_INDEX_STRATEGY,
        },
      ]),
    ) as RegistryItemTypeMap<RegistryBuildSource>,
    stripVariables: config.stripVariables ?? [...DEFAULT_STRIP_VARIABLES],
    targetPaths: config.targetPaths ?? {},
    themes: config.themes
      ? {
          ...config.themes,
          cssVarKeys: config.themes.cssVarKeys ?? [...DEFAULT_THEME_CSS_VAR_KEYS],
          defaultRadius: config.themes.defaultRadius ?? DEFAULT_THEME_RADIUS,
          names: config.themes.names ?? [...DEFAULT_THEME_NAMES],
        }
      : undefined,
    branding: {
      ...DEFAULT_BRANDING,
      ...config.branding,
    },
  }
}
