import type {
  RegistryBuildComponentIndexEntryOptions,
  RegistryBuildComponentIndexImportOptions,
} from './component-index.types'

export const NEXTJS_COMPONENT_INDEX_HEADER = `// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build
// Do not edit this file directly.
import * as React from "react"

let dynamic: any
try { dynamic = (await import("next/dynamic.js")).default } catch { dynamic = () => () => null }
`

export function createNextjsComponentImport(options: RegistryBuildComponentIndexImportOptions) {
  return `const ${options.id} = dynamic(() => import("${options.componentPath}"), { ssr: ${String(options.ssr)} })\n`
}

export function createComponentIndexEntry(options: RegistryBuildComponentIndexEntryOptions) {
  const item = options.item

  return `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: ${JSON.stringify(item.files, null, 2)},
    component: ${options.id},
    source: "${item.source ?? ''}",
    categories: ${JSON.stringify(item.categories ?? [])},
    root_folder: "${item.root_folder}",
  },`
}
