export const VITE_COMPONENT_INDEX_HEADER = `// @ts-nocheck
// This file is autogenerated by @gentleduck/registry-build
// Do not edit this file directly.
import * as React from "react"
`

export function createViteComponentImport(options: { componentPath: string; id: string }) {
  return `const ${options.id} = React.lazy(() => import("${options.componentPath}"))\n`
}
