import { defineSidebar } from './types'

export const duckAuthSidebar = defineSidebar([
  {
    title: '',
    items: [
      { title: 'Introduction', href: '/duck-auth/introduction' },
      { title: 'Installation', href: '/duck-auth/installation' },
      { title: 'Concepts & glossary', href: '/duck-auth/concepts' },
      { title: 'How it compares', href: '/duck-auth/comparison' },
      { title: 'FAQ', href: '/duck-auth/faq' },
    ],
  },
  {
    title: 'Core',
    href: '/duck-auth/core',
    items: [
      { title: 'Overview', href: '/duck-auth/core' },
      { title: 'Sessions', href: '/duck-auth/core/sessions' },
      { title: 'Identities', href: '/duck-auth/core/identities' },
      { title: 'Passwords', href: '/duck-auth/core/passwords' },
      { title: 'Flows', href: '/duck-auth/core/flows' },
      { title: 'Orgs (multi-tenancy)', href: '/duck-auth/core/orgs' },
      { title: 'Operations', href: '/duck-auth/core/operations' },
      { title: 'Errors', href: '/duck-auth/core/errors' },
      { title: 'Events', href: '/duck-auth/core/events' },
      { title: 'Anomaly detection', href: '/duck-auth/core/anomaly' },
      { title: 'Compliance presets', href: '/duck-auth/core/compliance' },
      {
        title: 'Transports',
        href: '/duck-auth/core/transports',
        collapsible: true,
        defaultOpen: false,
        items: [
          { title: 'Overview', href: '/duck-auth/core/transports' },
          { title: 'CookieTransport', href: '/duck-auth/core/transports/cookie' },
          { title: 'BearerTransport', href: '/duck-auth/core/transports/bearer' },
          { title: 'JwtTransport', href: '/duck-auth/core/transports/jwt' },
          { title: 'CompositeTransport', href: '/duck-auth/core/transports/composite' },
          { title: 'DPoP', href: '/duck-auth/core/transports/dpop' },
        ],
      },
    ],
  },
  {
    title: 'Providers',
    href: '/duck-auth/providers',
    items: [
      { title: 'Overview', href: '/duck-auth/providers' },
      { title: 'Password', href: '/duck-auth/providers/password' },
      { title: 'Magic link', href: '/duck-auth/providers/magic-link' },
      {
        title: 'OAuth',
        href: '/duck-auth/providers/oauth',
        collapsible: true,
        defaultOpen: false,
        items: [
          { title: 'Overview', href: '/duck-auth/providers/oauth' },
          { title: 'Google', href: '/duck-auth/providers/oauth/google' },
          { title: 'GitHub', href: '/duck-auth/providers/oauth/github' },
          { title: 'Microsoft', href: '/duck-auth/providers/oauth/microsoft' },
          { title: 'Apple', href: '/duck-auth/providers/oauth/apple' },
          { title: 'LinkedIn', href: '/duck-auth/providers/oauth/linkedin' },
          { title: 'Discord', href: '/duck-auth/providers/oauth/discord' },
        ],
      },
      { title: 'Passkey (WebAuthn)', href: '/duck-auth/providers/passkey' },
      { title: 'API key', href: '/duck-auth/providers/api-key' },
      { title: 'SAML', href: '/duck-auth/providers/saml' },
    ],
  },
  {
    title: 'Adapters',
    href: '/duck-auth/adapters',
    items: [
      { title: 'Overview', href: '/duck-auth/adapters' },
      { title: 'Memory', href: '/duck-auth/adapters/memory' },
      { title: 'Redis', href: '/duck-auth/adapters/redis' },
      { title: 'SQL bridge + Drizzle', href: '/duck-auth/adapters/sql' },
    ],
  },
  {
    title: 'Channels',
    href: '/duck-auth/channels',
    items: [
      { title: 'Overview', href: '/duck-auth/channels' },
      { title: 'Console / Test / Noop', href: '/duck-auth/channels/console' },
      { title: 'SMTP', href: '/duck-auth/channels/smtp' },
      { title: 'Resend', href: '/duck-auth/channels/resend' },
      { title: 'AWS SES', href: '/duck-auth/channels/ses' },
      { title: 'Twilio (SMS)', href: '/duck-auth/channels/twilio' },
      { title: 'Web Push', href: '/duck-auth/channels/webpush' },
    ],
  },
  {
    title: 'Server adapters',
    href: '/duck-auth/server',
    items: [
      { title: 'Overview', href: '/duck-auth/server' },
      { title: 'Express', href: '/duck-auth/server/express' },
      { title: 'Hono', href: '/duck-auth/server/hono' },
      { title: 'Next.js', href: '/duck-auth/server/next' },
      { title: 'Fastify', href: '/duck-auth/server/fastify' },
      { title: 'Koa', href: '/duck-auth/server/koa' },
      { title: 'Elysia', href: '/duck-auth/server/elysia' },
      { title: 'NestJS', href: '/duck-auth/server/nestjs' },
      { title: 'gRPC', href: '/duck-auth/server/grpc' },
      { title: 'Generic (Web Fetch)', href: '/duck-auth/server/generic' },
    ],
  },
  {
    title: 'Client libraries',
    href: '/duck-auth/client',
    items: [
      { title: 'Overview', href: '/duck-auth/client' },
      { title: 'Vanilla', href: '/duck-auth/client/vanilla' },
      { title: 'React', href: '/duck-auth/client/react' },
      { title: 'Vue', href: '/duck-auth/client/vue' },
      { title: 'Svelte', href: '/duck-auth/client/svelte' },
    ],
  },
  {
    title: 'Guides',
    items: [
      { title: 'Quick start', href: '/duck-auth/guides' },
      { title: 'Adding MFA', href: '/duck-auth/guides/mfa' },
      { title: 'Bridging to duck-iam', href: '/duck-auth/guides/iam-bridge' },
    ],
  },
  {
    title: 'Advanced',
    items: [
      { title: 'Production hardening', href: '/duck-auth/advanced/security' },
      { title: 'CLI reference', href: '/duck-auth/advanced/cli' },
      { title: 'OIDC discovery', href: '/duck-auth/advanced/oidc' },
      { title: 'OpenAPI generator', href: '/duck-auth/advanced/openapi' },
      { title: 'OpenTelemetry', href: '/duck-auth/advanced/telemetry' },
      { title: 'i18n', href: '/duck-auth/advanced/i18n' },
      { title: 'Testing', href: '/duck-auth/advanced/testing' },
    ],
  },
  {
    title: 'Changelog',
    items: [{ title: 'Changelog', href: '/duck-auth/changelog' }],
  },
])
