import { defineSidebar } from './types'

export const duckUiSidebar = defineSidebar([
  {
    title: '',
    items: [
      { title: 'Introduction', href: '/duck-ui/introduction' },
      { title: 'theming', href: '/duck-ui/theming' },
      { title: 'javascript', href: '/duck-ui/javascript' },
      { title: 'faqs', href: '/duck-ui/faqs' },
    ],
  },
  {
    title: 'Changelog',
    items: [{ title: 'Changelog', href: '/duck-ui/changelog' }],
  },
  {
    title: 'Installation',
    items: [
      { title: 'installation', href: '/duck-ui/installation' },
      { title: 'next.js', href: '/duck-ui/installation/next' },
      { title: 'vite', href: '/duck-ui/installation/vite' },
      { title: 'astro', href: '/duck-ui/installation/astro' },
      { title: 'laravel', href: '/duck-ui/installation/laravel' },
      { title: 'react-router', href: '/duck-ui/installation/react-router' },
      { title: 'tanstack-start', href: '/duck-ui/installation/tanstack' },
      { title: 'tanstack-router', href: '/duck-ui/installation/tanstack-router' },
      { title: 'manual-installation', href: '/duck-ui/installation/manual' },
      { title: 'monorepo', href: '/duck-ui/installation/monorepo' },
    ],
  },
  {
    title: 'Components',
    items: [
      { title: 'accordion', href: '/duck-ui/components/accordion' },
      { title: 'alert', href: '/duck-ui/components/alert' },
      { title: 'alert-dialog', href: '/duck-ui/components/alert-dialog' },
      { title: 'aspect-ratio', href: '/duck-ui/components/aspect-ratio' },
      { title: 'avatar', href: '/duck-ui/components/avatar' },
      { title: 'badge', href: '/duck-ui/components/badge' },
      { title: 'breadcrumb', href: '/duck-ui/components/breadcrumb' },
      { title: 'button', href: '/duck-ui/components/button' },
      { title: 'button-group', href: '/duck-ui/components/button-group' },
      { title: 'calendar', href: '/duck-ui/components/calendar' },
      { title: 'card', href: '/duck-ui/components/card' },
      { title: 'carousel', href: '/duck-ui/components/carousel' },
      { title: 'chart', href: '/duck-ui/components/chart' },
      { title: 'checkbox', href: '/duck-ui/components/checkbox' },
      { title: 'collapsible', href: '/duck-ui/components/collapsible' },
      { title: 'combobox', href: '/duck-ui/components/combobox' },
      { title: 'command', href: '/duck-ui/components/command' },
      { title: 'context-menu', href: '/duck-ui/components/context-menu' },
      { title: 'data-table', href: '/duck-ui/components/data-table' },
      { title: 'date-picker', href: '/duck-ui/components/date-picker' },
      { title: 'dialog', href: '/duck-ui/components/dialog' },
      { title: 'direction', href: '/duck-ui/components/direction' },
      { title: 'drawer', href: '/duck-ui/components/drawer' },
      { title: 'dropdown-menu', href: '/duck-ui/components/dropdown-menu' },
      { title: 'empty', href: '/duck-ui/components/empty' },
      { title: 'field', href: '/duck-ui/components/field' },
      { title: 'hover-card', href: '/duck-ui/components/hover-card' },
      { title: 'input', href: '/duck-ui/components/input' },
      { title: 'input-group', href: '/duck-ui/components/input-group' },
      { title: 'input-otp', href: '/duck-ui/components/input-otp' },
      { title: 'item', href: '/duck-ui/components/item' },
      { title: 'json-editor', href: '/duck-ui/components/json-editor' },
      { title: 'kbd', href: '/duck-ui/components/kbd' },
      { title: 'label', href: '/duck-ui/components/label' },
      { title: 'menubar', href: '/duck-ui/components/menubar' },
      { title: 'navigation-menu', href: '/duck-ui/components/navigation-menu' },
      { title: 'pagination', href: '/duck-ui/components/pagination' },
      { title: 'popover', href: '/duck-ui/components/popover' },
      { title: 'preview-panel', href: '/duck-ui/components/preview-panel' },
      { title: 'progress', href: '/duck-ui/components/progress' },
      { title: 'radio-group', href: '/duck-ui/components/radio-group' },
      { title: 'React Hook Form', href: '/duck-ui/components/react-hook-form' },
      { title: 'resizable', href: '/duck-ui/components/resizable' },
      { title: 'scroll-area', href: '/duck-ui/components/scroll-area' },
      { title: 'select', href: '/duck-ui/components/select' },
      { title: 'separator', href: '/duck-ui/components/separator' },
      { title: 'sheet', href: '/duck-ui/components/sheet' },
      { title: 'Sidebar', href: '/duck-ui/components/sidebar' },
      { title: 'skeleton', href: '/duck-ui/components/skeleton' },
      { title: 'slider', href: '/duck-ui/components/slider' },
      { title: 'sonner', href: '/duck-ui/components/sonner' },
      { title: 'switch', href: '/duck-ui/components/switch' },
      { title: 'table', href: '/duck-ui/components/table' },
      { title: 'tabs', href: '/duck-ui/components/tabs' },
      { title: 'TanStack Form', href: '/duck-ui/components/tanstack-form' },
      { title: 'textarea', href: '/duck-ui/components/textarea' },
      { title: 'toggle', href: '/duck-ui/components/toggle' },
      { title: 'toggle-group', href: '/duck-ui/components/toggle-group' },
      { title: 'tooltip', href: '/duck-ui/components/tooltip' },
      { title: 'typography', href: '/duck-ui/components/typography' },
    ],
  },
])
