export const ASTRO_COMPONENT_INDEX_HEADER = `// This file is autogenerated by @gentleduck/registry-build
// Do not edit this file directly.
`

export function createAstroComponentImport() {
  throw new Error('Astro component index generation is not implemented yet.')
}

