import { describe, expect, test } from 'bun:test'
import type {
  IRegistryBuildComponentIndexAdapter,
  IRegistryBuildComponentIndexEntryOptions,
  IRegistryBuildComponentIndexImportOptions,
} from '../..'
import {
  createComponentIndexEntry,
  createNextjsComponentImport,
  createViteComponentImport,
  getComponentIndexAdapter,
  NEXTJS_COMPONENT_INDEX_HEADER,
  VITE_COMPONENT_INDEX_HEADER,
} from '../..'

describe('getComponentIndexAdapter', () => {
  test('returns nextjs adapter for "nextjs" framework', () => {
    const adapter = getComponentIndexAdapter('nextjs')

    expect(adapter).toBeDefined()
    expect(adapter.defaultHeader).toContain('dynamic')
  })

  test('returns vite adapter for "vite" framework', () => {
    const adapter = getComponentIndexAdapter('vite')

    expect(adapter).toBeDefined()
    expect(adapter.defaultHeader).toContain('React')
  })

  test('returns custom adapter for "custom" framework', () => {
    const adapter = getComponentIndexAdapter('custom')

    expect(adapter).toBeDefined()
    expect(adapter.defaultHeader).toBe('')
  })

  test('nextjs adapter renderImport contains "dynamic"', () => {
    const adapter = getComponentIndexAdapter('nextjs')
    const result = adapter.renderImport({ componentPath: './button', id: 'Button', ssr: false })

    expect(result).toContain('dynamic')
  })

  test('vite adapter renderImport contains "lazy"', () => {
    const adapter = getComponentIndexAdapter('vite')
    const result = adapter.renderImport({ componentPath: './button', id: 'Button', ssr: false })

    expect(result).toContain('lazy')
  })

  test('custom adapter renderImport returns empty string', () => {
    const adapter = getComponentIndexAdapter('custom')
    const result = adapter.renderImport({ componentPath: './button', id: 'Button', ssr: false })

    expect(result).toBe('')
  })
})

// ---------------------------------------------------------------------------
// Adapter shape contract
// ---------------------------------------------------------------------------

describe('adapter shape contract', () => {
  const frameworks = ['nextjs', 'vite', 'custom'] as const

  for (const fw of frameworks) {
    test(`${fw} adapter has all required properties`, () => {
      const adapter = getComponentIndexAdapter(fw)

      expect(typeof adapter.defaultHeader).toBe('string')
      expect(typeof adapter.renderImport).toBe('function')
      expect(typeof adapter.renderEntry).toBe('function')
    })
  }

  test('all adapters share the same renderEntry implementation', () => {
    const nextjs = getComponentIndexAdapter('nextjs')
    const vite = getComponentIndexAdapter('vite')
    const custom = getComponentIndexAdapter('custom')

    expect(nextjs.renderEntry).toBe(vite.renderEntry)
    expect(vite.renderEntry).toBe(custom.renderEntry)
  })
})

// ---------------------------------------------------------------------------
// Header content
// ---------------------------------------------------------------------------

describe('adapter headers', () => {
  test('nextjs header includes @ts-nocheck directive', () => {
    expect(NEXTJS_COMPONENT_INDEX_HEADER).toContain('@ts-nocheck')
  })

  test('nextjs header includes autogenerated notice', () => {
    expect(NEXTJS_COMPONENT_INDEX_HEADER).toContain('autogenerated by @gentleduck/registry-build')
  })

  test('nextjs header imports React', () => {
    expect(NEXTJS_COMPONENT_INDEX_HEADER).toContain('import * as React from "react"')
  })

  test('nextjs header includes next/dynamic fallback', () => {
    expect(NEXTJS_COMPONENT_INDEX_HEADER).toContain('next/dynamic.js')
    expect(NEXTJS_COMPONENT_INDEX_HEADER).toContain('try {')
    expect(NEXTJS_COMPONENT_INDEX_HEADER).toContain('catch')
  })

  test('vite header includes @ts-nocheck directive', () => {
    expect(VITE_COMPONENT_INDEX_HEADER).toContain('@ts-nocheck')
  })

  test('vite header includes autogenerated notice', () => {
    expect(VITE_COMPONENT_INDEX_HEADER).toContain('autogenerated by @gentleduck/registry-build')
  })

  test('vite header imports React', () => {
    expect(VITE_COMPONENT_INDEX_HEADER).toContain('import * as React from "react"')
  })

  test('vite header does NOT reference next/dynamic', () => {
    expect(VITE_COMPONENT_INDEX_HEADER).not.toContain('dynamic')
    expect(VITE_COMPONENT_INDEX_HEADER).not.toContain('next/')
  })

  test('custom adapter defaultHeader is empty', () => {
    const adapter = getComponentIndexAdapter('custom')
    expect(adapter.defaultHeader).toBe('')
  })

  test('nextjs adapter defaultHeader matches NEXTJS_COMPONENT_INDEX_HEADER', () => {
    const adapter = getComponentIndexAdapter('nextjs')
    expect(adapter.defaultHeader).toBe(NEXTJS_COMPONENT_INDEX_HEADER)
  })

  test('vite adapter defaultHeader matches VITE_COMPONENT_INDEX_HEADER', () => {
    const adapter = getComponentIndexAdapter('vite')
    expect(adapter.defaultHeader).toBe(VITE_COMPONENT_INDEX_HEADER)
  })
})

// ---------------------------------------------------------------------------
// Next.js renderImport
// ---------------------------------------------------------------------------

describe('createNextjsComponentImport', () => {
  test('embeds the component path in the import', () => {
    const result = createNextjsComponentImport({ componentPath: '@ui/button/button', id: '_Button', ssr: false })
    expect(result).toContain('@ui/button/button')
  })

  test('embeds the component identifier as variable name', () => {
    const result = createNextjsComponentImport({ componentPath: './x', id: '_MyComponent', ssr: false })
    expect(result).toContain('const _MyComponent')
  })

  test('ssr: false produces ssr: false in output', () => {
    const result = createNextjsComponentImport({ componentPath: './x', id: '_A', ssr: false })
    expect(result).toContain('ssr: false')
  })

  test('ssr: true produces ssr: true in output', () => {
    const result = createNextjsComponentImport({ componentPath: './x', id: '_A', ssr: true })
    expect(result).toContain('ssr: true')
  })

  test('ends with a newline', () => {
    const result = createNextjsComponentImport({ componentPath: './x', id: '_A', ssr: false })
    expect(result.endsWith('\n')).toBe(true)
  })

  test('handles paths with deep nesting', () => {
    const result = createNextjsComponentImport({
      componentPath: '@pkg/components/ui/forms/date-picker/date-picker',
      id: '_DatePicker',
      ssr: false,
    })
    expect(result).toContain('@pkg/components/ui/forms/date-picker/date-picker')
    expect(result).toContain('_DatePicker')
  })

  test('handles paths with special characters', () => {
    const result = createNextjsComponentImport({ componentPath: './@scope/my-lib', id: '_ScopedLib', ssr: false })
    expect(result).toContain('./@scope/my-lib')
  })
})

// ---------------------------------------------------------------------------
// Vite renderImport
// ---------------------------------------------------------------------------

describe('createViteComponentImport', () => {
  test('uses React.lazy for dynamic import', () => {
    const result = createViteComponentImport({ componentPath: './button', id: '_Button' })
    expect(result).toContain('React.lazy')
    expect(result).toContain('import("./button")')
  })

  test('embeds the component identifier as variable name', () => {
    const result = createViteComponentImport({ componentPath: './x', id: '_Dialog' })
    expect(result).toContain('const _Dialog')
  })

  test('ends with a newline', () => {
    const result = createViteComponentImport({ componentPath: './x', id: '_A' })
    expect(result.endsWith('\n')).toBe(true)
  })

  test('does NOT include ssr option (vite has no ssr param)', () => {
    const result = createViteComponentImport({ componentPath: './x', id: '_A' })
    expect(result).not.toContain('ssr')
  })

  test('vite adapter ignores ssr option passed through getComponentIndexAdapter', () => {
    const adapter = getComponentIndexAdapter('vite')
    const withSsrTrue = adapter.renderImport({ componentPath: './x', id: '_A', ssr: true })
    const withSsrFalse = adapter.renderImport({ componentPath: './x', id: '_A', ssr: false })
    expect(withSsrTrue).toBe(withSsrFalse)
    expect(withSsrTrue).not.toContain('ssr')
  })
})

// ---------------------------------------------------------------------------
// createComponentIndexEntry (shared across all adapters)
// ---------------------------------------------------------------------------

describe('createComponentIndexEntry', () => {
  const minimalItem = {
    name: 'button',
    type: 'registry:ui' as const,
    root_folder: 'components/ui',
  }

  test('renders the component name as key', () => {
    const result = createComponentIndexEntry({ id: '_Button', item: minimalItem })
    expect(result).toContain('"button"')
  })

  test('renders the id as component reference', () => {
    const result = createComponentIndexEntry({ id: '_Button', item: minimalItem })
    expect(result).toContain('component: _Button')
  })

  test('renders type', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result).toContain('type: "registry:ui"')
  })

  test('renders root_folder', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result).toContain('root_folder: "components/ui"')
  })

  test('renders empty description when missing', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result).toContain('description: ""')
  })

  test('renders description when provided', () => {
    const result = createComponentIndexEntry({
      id: '_X',
      item: { ...minimalItem, description: 'A primary button' },
    })
    expect(result).toContain('description: "A primary button"')
  })

  test('renders empty source when missing', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result).toContain('source: ""')
  })

  test('renders source when provided', () => {
    const result = createComponentIndexEntry({
      id: '_X',
      item: { ...minimalItem, source: 'https://example.com' },
    })
    expect(result).toContain('source: "https://example.com"')
  })

  test('renders empty categories when missing', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result).toContain('categories: []')
  })

  test('renders categories when provided', () => {
    const result = createComponentIndexEntry({
      id: '_X',
      item: { ...minimalItem, categories: ['forms', 'inputs'] },
    })
    expect(result).toContain('categories: ["forms","inputs"]')
  })

  test('renders registryDependencies', () => {
    const result = createComponentIndexEntry({
      id: '_X',
      item: { ...minimalItem, registryDependencies: ['tooltip', 'popover'] },
    })
    expect(result).toContain('"tooltip"')
    expect(result).toContain('"popover"')
  })

  test('renders files array', () => {
    const result = createComponentIndexEntry({
      id: '_X',
      item: {
        ...minimalItem,
        files: [{ path: 'components/ui/button.tsx', type: 'registry:ui' }],
      },
    })
    expect(result).toContain('button.tsx')
    expect(result).toContain('registry:ui')
  })

  test('handles item with no files', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result).toBeDefined()
    expect(typeof result).toBe('string')
  })

  test('handles item with no registryDependencies', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result).toBeDefined()
  })

  test('handles item with multiple files', () => {
    const result = createComponentIndexEntry({
      id: '_DatePicker',
      item: {
        ...minimalItem,
        name: 'date-picker',
        files: [
          { path: 'components/ui/date-picker/date-picker.tsx', type: 'registry:ui' },
          { path: 'components/ui/date-picker/calendar.tsx', type: 'registry:ui' },
          { path: 'components/ui/date-picker/utils.ts', type: 'registry:ui' },
        ],
      },
    })
    expect(result).toContain('date-picker.tsx')
    expect(result).toContain('calendar.tsx')
    expect(result).toContain('utils.ts')
  })

  test('trailing comma at end of entry', () => {
    const result = createComponentIndexEntry({ id: '_X', item: minimalItem })
    expect(result.trimEnd().endsWith(',')).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// Adapter isolation (each call returns a fresh object)
// ---------------------------------------------------------------------------

describe('adapter isolation', () => {
  test('separate calls return distinct adapter objects', () => {
    const a = getComponentIndexAdapter('nextjs')
    const b = getComponentIndexAdapter('nextjs')
    expect(a).not.toBe(b)
    expect(a).toEqual(b)
  })

  test('mutating one adapter does not affect a new adapter', () => {
    const a = getComponentIndexAdapter('vite')
    ;(a as any).defaultHeader = 'MUTATED'
    const b = getComponentIndexAdapter('vite')
    expect(b.defaultHeader).toBe(VITE_COMPONENT_INDEX_HEADER)
  })
})

// ---------------------------------------------------------------------------
// Edge cases: empty / single / multiple component lists through renderImport
// ---------------------------------------------------------------------------

describe('adapter with varying component counts', () => {
  const frameworks = ['nextjs', 'vite', 'custom'] as const

  for (const fw of frameworks) {
    test(`${fw}: renderImport with empty componentPath`, () => {
      const adapter = getComponentIndexAdapter(fw)
      const result = adapter.renderImport({ componentPath: '', id: '_Empty', ssr: false })
      expect(typeof result).toBe('string')
    })
  }

  test('nextjs: multiple sequential renderImport calls produce independent results', () => {
    const adapter = getComponentIndexAdapter('nextjs')
    const a = adapter.renderImport({ componentPath: './button', id: '_Button', ssr: false })
    const b = adapter.renderImport({ componentPath: './dialog', id: '_Dialog', ssr: true })

    expect(a).toContain('_Button')
    expect(a).toContain('./button')
    expect(a).not.toContain('_Dialog')

    expect(b).toContain('_Dialog')
    expect(b).toContain('./dialog')
    expect(b).not.toContain('_Button')
  })

  test('vite: multiple sequential renderImport calls produce independent results', () => {
    const adapter = getComponentIndexAdapter('vite')
    const a = adapter.renderImport({ componentPath: './alert', id: '_Alert', ssr: false })
    const b = adapter.renderImport({ componentPath: './card', id: '_Card', ssr: false })

    expect(a).toContain('_Alert')
    expect(a).not.toContain('_Card')
    expect(b).toContain('_Card')
    expect(b).not.toContain('_Alert')
  })
})

// ---------------------------------------------------------------------------
// renderEntry with rich item data
// ---------------------------------------------------------------------------

describe('createComponentIndexEntry with rich items', () => {
  test('handles item with all optional fields populated', () => {
    const richItem = {
      name: 'combobox',
      type: 'registry:ui' as const,
      root_folder: 'components/ui',
      description: 'An autocomplete combobox component',
      source: 'https://github.com/example/combobox',
      categories: ['forms', 'inputs', 'autocomplete'],
      registryDependencies: ['popover', 'command', 'badge'],
      files: [{ path: 'components/ui/combobox.tsx', type: 'registry:ui' as const }],
      dependencies: ['cmdk'],
      devDependencies: ['@types/cmdk'],
    }

    const result = createComponentIndexEntry({ id: '_Combobox', item: richItem })

    expect(result).toContain('"combobox"')
    expect(result).toContain('An autocomplete combobox component')
    expect(result).toContain('https://github.com/example/combobox')
    expect(result).toContain('autocomplete')
    expect(result).toContain('command')
    expect(result).toContain('component: _Combobox')
  })

  test('handles item with empty arrays', () => {
    const item = {
      name: 'separator',
      type: 'registry:ui' as const,
      root_folder: 'components/ui',
      registryDependencies: [],
      files: [],
      categories: [],
    }

    const result = createComponentIndexEntry({ id: '_Separator', item })
    expect(result).toContain('registryDependencies: []')
    expect(result).toContain('categories: []')
  })

  test('handles item name with many hyphens', () => {
    const item = {
      name: 'my-very-long-component-name',
      type: 'registry:ui' as const,
      root_folder: 'components/ui',
    }

    const result = createComponentIndexEntry({ id: '_MyVeryLongComponentName', item })
    expect(result).toContain('"my-very-long-component-name"')
    expect(result).toContain('component: _MyVeryLongComponentName')
  })
})
