import "../unist-BYKbr-MG.js";
import "../index--_dZRx38.js";
import { DocsVeliteConfigOptions, createDocsVeliteConfig, docsVeliteConfig } from "./config.js";
import { t as rhypeMetadataPlugin } from "../metadata-plugin-CGpIunEy.js";
import { t as rehypeMermaid } from "../rehype-mermaid-BAqbt3sI.js";
import { t as rehypeNpmCommand } from "../rehype-npm-command-ukfNONz6.js";
import { t as rehypePreBlockSource } from "../rehype-pre-block-source-Dsui2-09.js";
import { t as rehypeTitle } from "../rehype-title-Cl5DscyF.js";
import "./plugins/index.js";
import { cleanTocItems } from "./utils.js";
export { type DocsVeliteConfigOptions, cleanTocItems, createDocsVeliteConfig, docsVeliteConfig, rehypeMermaid, rehypeNpmCommand, rehypePreBlockSource, rehypeTitle, rhypeMetadataPlugin };