import type { RegistryEntry } from '../registry-schema'

// Examples share the same shell — registry:example, files: [], rooted under
// `<name>`, name suffixed with `-examples`. A builder collapses 60+ entries
// from ~450 LoC to ~80 LoC and makes deps audit-able at a glance.
function example(name: string, deps: string[] = []): RegistryEntry {
  return {
    files: [],
    name: `${name}-examples`,
    registryDependencies: deps,
    root_folder: name,
    type: 'registry:example',
  }
}

export const registryExamples: RegistryEntry[] = [
  example('accordion', ['accordion']),
  example('alert', ['alert']),
  example('alert-dialog', ['alert-dialog']),
  example('avatar', ['avatar']),
  example('badge', ['badge']),
  example('button', ['button']),
  example('breadcrumb', ['breadcrumb']),
  example('dialog', ['dialog']),
  example('command', ['command']),
  example('card', ['card']),
  example('calendar', ['calendar']),
  example('drawer', ['drawer']),
  example('direction', ['direction']),
  example('hover-card', ['hover-card']),
  example('input', ['input']),
  example('label', ['label']),
  example('progress', ['progress']),
  example('radio-group', ['radio-group']),
  example('scroll-area', ['scroll-area']),
  example('select', ['select']),
  example('separator', ['separator']),
  example('sheet', ['sheet']),
  example('skeleton', ['skeleton']),
  example('slider', ['slider']),
  example('switch', ['switch']),
  example('sonner', ['sonner']),
  example('tabs', ['tabs']),
  example('textarea', ['textarea']),
  example('toggle', ['toggle']),
  example('toggle-group', ['toggle-group']),
  example('tooltip', ['tooltip']),
  example('aspect-ratio', ['aspect-ratio']),
  example('typography', ['typography']),
  example('table', ['table']),
  example('resizable', ['resizable']),
  example('pagination', ['pagination']),
  example('checkbox', ['checkbox']),
  example('carousel', ['carousel']),
  example('date-picker', ['calendar', 'popover', 'button']),
  example('popover', ['popover']),
  example('menubar', ['menubar']),
  example('dropdown-menu', ['dropdown-menu']),
  example('combobox', ['combobox']),
  example('collapsible', ['collapsible']),
  example('input-otp', ['input-otp', 'button', 'field']),
  example('chart', ['chart']),
  example('navigation-menu', ['navigation-menu']),
  example('context-menu', ['context-menu']),
  example('data-table', ['data-table', 'table']),
  example('cva'),
  example('button-group', ['button-group']),
  example('kbd', ['kbd']),
  example('empty', ['empty']),
  example('field', ['field']),
  example('item', ['item']),
  example('input-group', ['input-group']),
  example('json-editor', ['json-editor']),
  example('theme-toggle'),
  example('preview-panel', ['preview-panel']),
  example('sidebar', ['sidebar']),
  example('upload', ['upload']),
  example('form', [
    'button',
    'checkbox',
    'field',
    'input',
    'input-group',
    'radio-group',
    'select',
    'switch',
    'textarea',
  ]),
]
