name: Semgrep SAST

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    - cron: "45 6 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Semgrep
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: >-
            p/typescript
            p/react
            p/javascript
            p/owasp-top-ten
            p/security-audit
            p/secrets
            p/supply-chain
            p/cwe-top-25
        continue-on-error: true

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@dc73d59c2d7bd4f8194098a91219eeee6d8a1719 # v4
        with:
          sarif_file: semgrep.sarif
          category: semgrep
