// Generated by duck-md build
import type __vc from '../duck-md.config'

type Collections = (typeof __vc)['collections']

export type Docs = NonNullable<Collections['docs']['schema']>['_output']
export declare const docs: Docs[]

export type DuckCalendar = NonNullable<Collections['duckCalendar']['schema']>['_output']
export declare const duckCalendar: DuckCalendar[]

export type DuckCli = NonNullable<Collections['duckCli']['schema']>['_output']
export declare const duckCli: DuckCli[]

export type DuckGen = NonNullable<Collections['duckGen']['schema']>['_output']
export declare const duckGen: DuckGen[]

export type DuckHooks = NonNullable<Collections['duckHooks']['schema']>['_output']
export declare const duckHooks: DuckHooks[]

export type DuckIam = NonNullable<Collections['duckIam']['schema']>['_output']
export declare const duckIam: DuckIam[]

export type DuckLazy = NonNullable<Collections['duckLazy']['schema']>['_output']
export declare const duckLazy: DuckLazy[]

export type DuckLibs = NonNullable<Collections['duckLibs']['schema']>['_output']
export declare const duckLibs: DuckLibs[]

export type DuckMotion = NonNullable<Collections['duckMotion']['schema']>['_output']
export declare const duckMotion: DuckMotion[]

export type DuckPrimitives = NonNullable<Collections['duckPrimitives']['schema']>['_output']
export declare const duckPrimitives: DuckPrimitives[]

export type DuckQuery = NonNullable<Collections['duckQuery']['schema']>['_output']
export declare const duckQuery: DuckQuery[]

export type DuckRegistryBuild = NonNullable<Collections['duckRegistryBuild']['schema']>['_output']
export declare const duckRegistryBuild: DuckRegistryBuild[]

export type DuckShortcut = NonNullable<Collections['duckShortcut']['schema']>['_output']
export declare const duckShortcut: DuckShortcut[]

export type DuckState = NonNullable<Collections['duckState']['schema']>['_output']
export declare const duckState: DuckState[]

export type DuckTemplate = NonNullable<Collections['duckTemplate']['schema']>['_output']
export declare const duckTemplate: DuckTemplate[]

export type DuckTtest = NonNullable<Collections['duckTtest']['schema']>['_output']
export declare const duckTtest: DuckTtest[]

export type DuckTtlog = NonNullable<Collections['duckTtlog']['schema']>['_output']
export declare const duckTtlog: DuckTtlog[]

export type DuckUi = NonNullable<Collections['duckUi']['schema']>['_output']
export declare const duckUi: DuckUi[]

export type DuckUpload = NonNullable<Collections['duckUpload']['schema']>['_output']
export declare const duckUpload: DuckUpload[]

export type DuckVariants = NonNullable<Collections['duckVariants']['schema']>['_output']
export declare const duckVariants: DuckVariants[]

export type DuckVim = NonNullable<Collections['duckVim']['schema']>['_output']
export declare const duckVim: DuckVim[]

export type Www = NonNullable<Collections['www']['schema']>['_output']
export declare const www: Www[]

